version: '3.9'

services:
  my-mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-vol:/data/db
      - ./db/mongo.conf:/etc/mongo  
    networks:
      - app-network
    ports:
      - 27017:27017

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1 
    ports:
      - 8080:8080
    command: -v start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb-vol: